<?php

function title()
{
    return [
        "SquareBol",
        "Dead End Defense",
        "Skill Roll",
        "Ninja Roll 2",
        "Armored Attack",
        "Star command",
        "The Gaming Quiz",
        "Bridge Thing Instalment 2",
        "Rag doll killer idle",
        "Purple Box 3",
        "Inner Zombie",
        "Bear&Bees",
        "Fire In The Hole 2",
        "Attack Of The Bean Men",
        "The Lumbering Dead",
        "Typhoo",
        "Edward",
        "Heart",
        "Alien Evasion",
        "A Mage\\\'s Day",
        "Brave Harp",
        "VoidGale",
        "The Cursed Castle Escape",
        "Neko-Don",
        "Legend of Marilia",
        "The Stairway",
        "I am Zombie",
        "Busker Panic",
        "Bouncy Draw",
        "Battle City",
        "4th and Goal 2011",
        "247 Mahjong",
        "Steal Gold And Escape 3",
        "Johnny Finder 2",
        "City Smile",
        "Legitimate TD",
        "Figground",
        "The Slugs!",
        "Final Fantasy Sonic x4",
        "Zombie Riot",
        "Green Protector",
        "Droid Apocalypse 2099",
        "Leaping Luchadores",
        "Not correct school",
        "Fugashu",
        "Evil Nights",
        "Slardar Defense [BETA]",
        "Number Cruncher 1.0",
        "Remove your way",
        "Defense 1943",
        "Stickman Tower Defense",
        "Scared Alien",
        "Bouncer",
        "Vehicle Tower Defense",
        "turtle defense",
        "GravityPong 1PC-Multiplayer",
        "Zassin",
        "Magnetism",
        "Maze Tosser",
        "Knife",
        "Fairy Cubes Online",
        "Awesome Dress Up",
        "Mystery Castle Secret Escape",
        "Goodbye Sadness",
        "Sneaky\\\'s Quest",
        "The Gauntlet",
        "RPG Tower Defense 1.5",
        "Don\\\'t Let \\\'Em Touch",
        "TechnoMice",
        "DONT CLICK THE BUTTON! (Deluxe edition)",
        "CoinAthlon",
        "The Caverns",
        "The Stress Ferret",
        "Crack the Nut",
        "Integrated Tower Defense ",
        "Puzzle Boy",
        "Make your own stick man",
        "The Tunnel of Horror ...",
        "Parking Hooligan",
        "Find Morrrr: Global",
        "Graveyard of Drunken Souls",
        "Vector Cubed",
        "Season of War",
        "Wigman Big Run",
        "Short Legs Want Rabbits",
        "SimpleRTS",
        "Megablob: Section 6",
        "Whooly & The lost Treasures",
        "Chute Defence",
        "Bob\\\'s World",
        "Crayon Blocks",
        "Air Attack FX",
        "Master of Basics: Flash Tutorial",
        "Are you an idiot?",
        "Stunt Crazy Trick or Treat",
        "Hubris",
        "Sewer Escape 2",
        "Night Gunner",
        "Penguin Plop",
        "Pushback",
        "Angry Toys 5 Differences",
        "Chaotic - Perim Protector",
        "Medieval Gunpowder",
        "connect master",
        "The Kittelutioning",
        "Experiments ",
        "Attack of the Chasers",
        "Atom Antics",
        "Pingu\\\'s Quest Mobile",
        "Kong Ball",
        "Hellbound Rampage",
        "Reys Quest 7: Fighter Rey!! (KL)",
        "Defendfishboat",
        "Background Survival",
        "Vector Rush",
        "The Factory",
        "Drum Machine - GG",
        "Diet",
        "Summer",
        "Showroom",
        "Reckless Advance",
        "Maze 4",
        "Monkey Boom",
        "Torch",
        "QuackTheDuck",
        "Who Am I?",
        "Sponge Bob: Knight\\\'s tournament",
        "Paper Cannon 2",
        "Deus Shift",
        "Rail Pioneer",
        "Younakon Adventure",
        "Trailer Racing 2: new multiplayer racing game",
        "Word Fission",
        "Virus",
        "Jade Monkey Beta",
        "Hop To The Top",
        "Bricks",
        "Giraffe Above",
        "Armored Ashura",
        "Multiplayer Trouble",
        "The Bullet 2",
        "The Battle of Elementals",
        "Spinner",
        "Memories Demo",
        "Find the Red Button",
        "Zombie Mania",
        "Paths",
        "Exorbis",
        "Ultimate Cruise",
        "Roll And Jump",
        "Raw Cat Lawn Chair",
        "Danger Squadron!",
        "Insect Wave",
        "Social",
        "Redcoat Invasion",
        "Statistic Idle",
        "Call of Robloxia 5 - Roblox At War",
        "Bubble wrap",
        "daymare Invaders",
        "The Dead Pirate\\\'s Chest",
        "Ten Pynn Bowling",
        "Wreck Raider",
        "Vampire Valentine",
        "Gravity Football Champions 2012 (v1.1)",
        "Ashtons Family Resort",
        "My Hero Dress Up",
        "Embrangle",
        "Palin Hero",
        "Iron Ball Cannon - v-0.1",
        "Dream world 5 Differences",
        "Super Belly Boarder",
        "Othexo",
        "The Maths quiz",
        "Narbll",
        "Strategic Mayhem",
        "Anime Motocross",
        "City Racing",
        "Dodge The Blocks",
        "Transformice Dress Up",
        "Free Running",
        "World Of Doodles",
        "Dry Eternity RPG",
        "Bomb Chain Mobile",
        ".explore",
        "Hidden Master 9",
        "Stringer Mission",
        "King Pong",
        "NyanCat Hyperspace Adventures",
        "7 Stones Room Escape",
        "Ancient Girl Room Escape",
        "Phantom Mansion - The Blue Ballroom",
        "Magic Towers Solitaire 1.5",
        "Warnet - The Elixir of Youth",
        "Virus Wars",
        "Chicken Escape",
        "21 Balloons",
        "Pikachu Coloring Game",
        "Math Attack",
        "Orb Destruction: World Savior",
        "MiniMiner 3D Alpha",
        "GabCab",
        "Color Outrage",
        "Bloods Vs Crips",
        "Space Thieves",
        "Polimon",
        "BETA Sector",
        "Martian Chess",
        "Trifferences",
        "Libra Battle",
        "Zone of War",
        "Ball Revamped",
        "cling",
        "Chess AI Game",
        "Boombang Friends",
        "Kongregate Chat Sketcher Beta",
        "Sudoku-Puzzle",
        "Happy New Year",
        "SandDrops",
        "CrateRun",
        "Parasite X",
        "two player snake",
        "Name That Sports Car",
        "Fish For Food",
        "Mayaboom",
        "Scarecrow. Battle for the Harvest ",
        "Superstar Football",
        "Duck Tiles",
        "Snowbowl",
        "Photobox-Land",
        "JugglePix",
        "Pray N\\\' Spray Beta",
        "Diamond Bridge Escape",
        "SuperStick RPG 3",
        "Chobots Sweet Battle-3",
        "Sunrise",
        "Gem Grab Mobile",
        "Forest of Echoes",
        "Pig Nukem",
        "Robot Territories",
        "Wheelbox: The Fallen Star",
        "Aero Tortuga",
        "Dinosaur Goofs",
        "Rebound",
        "Dodge Fishy",
        "Asteroid Deluxe",
        "For Science!!!",
        "Redhatman",
        "Return of the Squid - Prologue",
        "JACKO IN HELL",
        "Updated",
        "Royal Envoy",
        "Spirit Hunter",
        "Parachute Retro",
        "MicroKong\\\'s Quest to Find the Banana",
        "Leaving Your Room 10",
        "BeatBox v1.0",
        "Farm Mania",
        "Parking Space 3",
        "shooter",
        "Timeline Runner 0-",
        "Anti- Cast",
        "The Square",
        "GlomboPOP",
        "University of Perceptions - Adventure",
        "Stretch The Puzzle: Holiday Gift",
        "Unity Freeroam",
        "Build & Destroy Live",
        "The Treasure Cave",
        "Urban Sniper 4",
        "Dream island",
        "Barn Yarn",
        "Spartaa\\\'s Run",
        "Turkey Hunt 2",
        "Zombie Outbreak",
        "Greemlins: Christmas Fires",
        "Escape the Zoo",
        "Ultimate Kongregate Quiz",
        "Comic Adventures of Mr. FFFUUUUUUU",
        "Gluddle",
        "MOCS",
        "Fuli",
        "Paths",
        "Swoopa",
        "Twin Bed Room Escape",
        "DONT CLICK THE BUTTON! Epilouge",
        "Creepy Creeps",
        "Ultimate Rally Challenge",
        "JUGGERNAUT: Awakening",
        "Colliderix Level Pack",
        "Idle Space II",
        "Sobics School",
        "Light it",
        "Contract",
        "Blue Balls",
        "Solitaire",
        "Pixel Paths",
        "Hit Logic",
        "Manymaze",
        "BioBots",
        "Gridlock Buster",
        "Prismatis",
        "Scroll Lock Mobile",
        "Unstack",
        "Boxheaded",
        "The Beatles Quiz",
        "Once Upon A Video Game",
        "Labyrinthe Twist",
        "Gloid",
        "Detetive Lemanto 3",
        "DarkBase Alien RTS",
        "Battleship",
        "Fences",
        "6 Peaks Solitaire",
        "Spacexx",
        "Me, Wake Up! Mini: Broccoli",
        "French Village Romanse Game",
        "Michael Jackson : The last Dance",
        "The Travelling Salesman",
        "Logo Finder III",
        "The Game Without a Name",
        "Nimbus Warrior",
        "BallMan Platform",
        "Agent B10 2",
        "CCCPirates",
        "Boudicca",
        "Stuck in Time - Demo",
        "Spaceship hallway Star Wars",
        "Beast Warrior",
        "Aetherpunk",
        "Catastrophic Construction",
        "Bombators Multiplayer",
        "Detetive Lemanto 2",
        "Tomb Defender",
        "Puppy Fetch",
        "World Reaction",
        "Neon Bounce",
        "DUBSTEP K",
        "ModRacing Xtreme Beta",
        "Roblox the noob adv",
        "Kuller",
        "Employee Firm Escape",
        "Head Defense",
        "Bionoids",
        "Simplicity",
        "Crawl",
        "Jelly Towers",
        "Illusion Escape",
        "AdvanSnake",
        "Thrower2",
        "Setti",
        "Run Box",
        "Five Minute Finder",
        "P*NG INVADERS",
        "My 8bit Valentine",
        "Tower of Wizard",
        "D-Evo",
        "Algorithm Crew: Proving Ground",
        "Flags And Countries",
        "Sudoku Safari",
        "Grid Control",
        "Nekoballoon",
        "Dropple 2",
        "Archery 3D",
        "Exer",
        "Snake Mayhem",
        "Le Manoir",
        "Guess The Password To Win Kreds!!!",
        "Terminator Car ",
        "The Last Square",
        "Super Avoider",
        "Pacmad",
        "The Heart Attack",
        "Escape The Hatch",
        "Heavily Armed",
        "Drop Block Game",
        "The Walkway DEMO",
        "Bee Dodger <3",
        "Treevolution",
        "Assembler 2 Mobile",
        "The Beadles",
        "Beta Force",
        "Killing Road",
        "Light Orbs 2",
        "DuoBlaster",
        "Goo Ball Madness - Demo",
        "Ninja Birds X : Old Arcade Game X by Cobalt Play Games",
        "Boxhead Biever & Baby",
        "Greedy Spider",
        "Dark Reality: Two Doors",
        "Monkey King",
        "Twee",
        "Gem Defender",
        "Cobra Squad Rescue",
        "Mystic India Pop ",
        "Galaxies Invaded: Chapter 2",
        "Barnyard Balloon",
        "Squares:Reloaded",
        "Egg War 2",
        "Countries of Europe",
        "Farm Hero : Spot the Differences",
        "Jiggle Worms: The Battle",
        "Taxi Rush Hours",
        "Ice Run",
        "Major Drift Racing",
        "Crazy Taxi",
        "Chatgame",
        "Newgrounds Museum 2",
        "Flubber-Rise",
        "Last Stand v2",
        "Code Blue",
        "The Flood",
        "Metro Zombies",
        "Ticketless",
        "The Eater",
        "Insect Onslaught",
        "Cube Crush",
        "Blitz 13",
        "Gum Drop Hop 2",
        "R.O.S",
        "Treasure of the Abandoned City",
        "Timing",
        "Drag Bike Manager 2",
        "Pirates Vs Ninjas",
        "Physics Cup",
        "Crack in the Sky",
        "Roller Derby 20XX",
        "Airport Mania 2: Wild Trips",
        "The Tricky Tumblers 2",
        "Intervalo lucido del individuo inconsciente",
        "Puppet Guardian",
        "Robrun",
        "Paintball",
        "Storm",
        "BUG"
    ];
}
